---

# ansible-playbook -K -D -i inventory/hosts.yml playbook.yml --ask-vault-pass

- name: Zabbix
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    zabbix:

  roles:
    - ansibleguy.sw_zabbix
