# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - src: 'https://github.com/ansibleguy/infra_nginx.git'
    version: 'stable'
    name: 'ansibleguy.infra_nginx'

  - src: 'https://github.com/ansibleguy/infra_mariadb.git'
    version: 'stable'
    name: 'ansibleguy.infra_mariadb'

  - name: 'community.mysql'
    source: 'https://galaxy.ansible.com'

  - name: 'ansible.posix'
    source: 'https://galaxy.ansible.com'
