---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - src: 'ansibleguy.infra_nginx'
  - src: 'ansibleguy.infra_certs'
  - src: 'ansibleguy.infra_mariadb'

collections:
  - name: 'community.mysql'
  - name: 'ansible.posix'
