---
# external roles and collections to download
# install: ansible-galaxy install -r requirements.yml

roles:
  - name: 'oxlorg.certs'
    src: 'git+https://github.com/O-X-L/ansible-role-certs'

  - name: 'oxlorg.nginx'
    src: 'git+https://github.com/O-X-L/ansible-role-nginx'

  - name: 'oxlorg.mariadb'
    src: 'git+https://github.com/O-X-L/ansible-role-mariadb'

collections:
  - 'community.mysql'
  - 'ansible.posix'
  - 'community.crypto'
