---

- name: Zabbix | Debian | Install | Agent V1 | Installing
  ansible.builtin.apt:
    name: "{{ ZABBIX_HC.packages.agent1 }}"
    state: latest

- name: Zabbix | Debian | Install | Agent V1 | Enabling service
  ansible.builtin.systemd:
    name: "{{ ZABBIX_HC.service.agent1 }}"
    state: started
    enabled: true
    daemon_reload: yes
