---

# https://support.zabbix.com/browse/ZBX-20451
- name: Zabbix | Install | Fix | Fixing breaking APT config in docker (Ticket ZBX-20451)
  ansible.builtin.lineinfile:
    path: '/etc/dpkg/dpkg.cfg.d/docker'
    search_string: 'path-exclude /usr/share/doc/*'
    line: '#path-exclude /usr/share/doc/*'
  ignore_errors: true
  register: zbx_fix_20451

- name: Zabbix | Install | Fix | Ask user
  ansible.builtin.pause:
    prompt: "You need to reboot the target system to apply the fix (else db import fails).
    If the target system is a docker-container - you may have to manually start it afterwards!
    Should we do this NOW? [yes/NO]"
  register: zbx_fix_20451_prompt_reboot
  when:
    - not no_prompts
    - zbx_fix_20451.failed is undefined or not zbx_fix_20451.failed
    - zbx_fix_20451.changed

- name: Zabbix | Install | Fix | Reboot to activate new config
  ansible.builtin.reboot:
    reboot_timeout: 60
  when: >
    (zbx_fix_20451.failed is undefined or not zbx_fix_20451.failed) and
    zbx_fix_20451.changed and
    (no_prompts or
    (zbx_fix_20451_prompt_reboot.user_input is defined and
    zbx_fix_20451_prompt_reboot.user_input in ['y', 'Y', 'yes', 'YES']))
  tags: molecule-notest
