---

- name: Zabbix | Debian | Install | Proxy | Checking if is installed
  ansible.builtin.apt:
    name: "{{ ZABBIX_HC.packages.proxy }}"
    state: present
  check_mode: true
  register: zbx_pkg_init_raw

- name: Zabbix | Debian | Install | Proxy | Installing
  ansible.builtin.apt:
    name: "{{ ZABBIX_HC.packages.proxy }}"
    state: latest

- name: Zabbix | Debian | Install | Proxy | Database tasks
  ansible.builtin.import_tasks: db.yml

- name: Zabbix | Debian | Install | Proxy | Enabling service
  ansible.builtin.systemd:
    name: "{{ ZABBIX_HC.service.proxy }}"
    state: started
    enabled: true
    daemon_reload: yes
