---

- name: Zabbix | Debian | Install | Proxy | Checking if is installed
  ansible.builtin.apt:
    name: 'zabbix-proxy-mysql'
    state: present
  check_mode: true

- name: Zabbix | Debian | Install | Proxy | Installing
  ansible.builtin.apt:
    name: "{{ ZABBIX_HC.packages.proxy[ZABBIX_CONFIG.proxy.database] }}"
    state: present

- name: Zabbix | Debian | Install | Proxy | Database tasks (<V6)
  ansible.builtin.import_tasks: db.yml
  vars:
    file_schema: "{{ ZABBIX_HC.file_mysql_proxy_lt6 }}"
  when: ZABBIX_CONFIG.version[0]|int < 6

- name: Zabbix | Debian | Install | Proxy | Database tasks (V6+)
  ansible.builtin.import_tasks: db.yml
  vars:
    file_schema: "{{ ZABBIX_HC.file_mysql_proxy_ge6 }}"
  when: ZABBIX_CONFIG.version[0]|int >= 6

- name: Zabbix | Debian | Install | Proxy | Enabling service
  ansible.builtin.systemd:
    name: "{{ ZABBIX_HC.service.proxy }}"
    state: started
    enabled: true
    daemon_reload: yes
