---

- name: Zabbix | Debian | Install | Proxy | Checking if is installed
  ansible.builtin.apt:
    name: 'zabbix-proxy-mysql'
    state: present
  check_mode: true

- name: Zabbix | Debian | Install | Proxy | Installing
  ansible.builtin.apt:
    name: "{{ ZABBIX_HC.packages.proxy }}"
    state: latest

- name: Zabbix | Debian | Install | Proxy | Database tasks
  ansible.builtin.import_tasks: db.yml
  vars:
    file_schema: "{{ ZABBIX_HC.file_mysql_proxy }}"

- name: Zabbix | Debian | Install | Proxy | Enabling service
  ansible.builtin.systemd:
    name: "{{ ZABBIX_HC.service.proxy }}"
    state: started
    enabled: true
    daemon_reload: yes
