---

- name: Zabbix | Install | Proxy | Applying fix
  ansible.builtin.import_tasks: fix_20451.yml
  when:
    - ansible_virtualization_role is defined
    - ansible_virtualization_role == 'guest'
    - "'docker' in ansible_virtualization_tech_guest"
  tags: molecule-notest

- name: Zabbix | Install | Proxy | Checking if is installed
  ansible.builtin.apt:
    name: 'zabbix-proxy-mysql'
    state: present
  check_mode: true

- name: Zabbix | Install | Proxy | Installing
  ansible.builtin.apt:
    name: "{{ ZABBIX_HC.packages.proxy[ZABBIX_CONFIG.proxy.database] }}"
    state: present

- name: Zabbix | Install | Proxy | Setting db import-file (<V6 - schema.sql.gz)
  ansible.builtin.set_fact:
    file_schema: "{{ ZABBIX_HC.file_mysql_proxy_lt6 }}"
  when:
    - ZABBIX_CONFIG.proxy.database == 'mysql'
    - ZABBIX_CONFIG.version is version('6.0', '<')

- name: Zabbix | Install | Proxy | Setting db import-file (V6.2 - proxy.sql)
  ansible.builtin.set_fact:
    file_schema: "{{ ZABBIX_HC.file_mysql_proxy_6_2 }}"
  when:
    - ZABBIX_CONFIG.proxy.database == 'mysql'
    - ZABBIX_CONFIG.version is version('6.2', '=')

- name: Zabbix | Install | Proxy | Setting db import-file (V6,V6.3+ - proxy.sql.gz)
  ansible.builtin.set_fact:
    file_schema: "{{ ZABBIX_HC.file_mysql_proxy_ge6 }}"
  when: >
    ZABBIX_CONFIG.proxy.database == 'mysql' and
    (ZABBIX_CONFIG.version is version('6.0', '=') or
    ZABBIX_CONFIG.version is version('6.2', '>'))

- name: Zabbix | Install | Proxy | Database tasks
  ansible.builtin.import_tasks: db.yml
  when: ZABBIX_CONFIG.proxy.database == 'mysql'

- name: Zabbix | Install | Proxy | SQLite Database
  ansible.builtin.shell: "sqlite3 {{ ZABBIX_CONFIG.proxy.settings.DBName | default('/usr/lib/zabbix/proxy.db', true) }} < {{ ZABBIX_HC.file_sqlite }}"
  when: >
    ZABBIX_CONFIG.proxy.database == 'sqlite' and
    (ZABBIX_CONFIG.version is version('6.0', '<') or

- name: Zabbix | Install | Proxy | Enabling service
  ansible.builtin.systemd:
    name: "{{ ZABBIX_HC.service.proxy }}"
    state: started
    enabled: true
    daemon_reload: yes
