# docker build -t mantest - < ./Dockerfile.j2
# docker run -it --privileged --name mantest mantest:latest /sbin/init --tmpfs /tmp --tmpfs /run --tmpfs /run/lock

FROM debian:11-slim

ENV container docker
ENV LC_ALL C
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y systemd systemd-sysv python3 sudo \
    && apt-get clean

# fix that kills db import: https://support.zabbix.com/browse/ZBX-20451
RUN sed -i 's|path-exclude /usr/share/doc/|# path-exclude /usr/share/doc/|g' /etc/dpkg/dpkg.cfg.d/docker

CMD ["/sbin/init"]
