---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-ag-zbx-tester
    docker_networks:
      - name: 'test-ag-zbx'
        ipam_config:
          - subnet: '192.168.8.0/24'
            gateway: '192.168.8.254'
    networks:
      - name: 'test-ag-zbx'
        ipv4_address: '192.168.8.1'
    etc_hosts: {zabbix.test.ansibleguy.net: '192.168.8.2'}
    groups: [grp_tester]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  - name: test-ag-zbx-srv
    networks:
      - name: 'test-ag-zbx'
        ipv4_address: '192.168.8.2'
    groups: [grp_targets]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  - name: test-ag-zbx-proxy
    networks:
      - name: 'test-ag-zbx'
        ipv4_address: '192.168.8.3'
    groups: [grp_targets]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  - name: test-ag-zbx-a2
    networks:
      - name: 'test-ag-zbx'
        ipv4_address: '192.168.8.4'
    groups: [grp_targets]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  - name: test-ag-zbx-a1
    networks:
      - name: 'test-ag-zbx'
        ipv4_address: '192.168.8.5'
    groups: [grp_targets]

    # docker config
    docker_host: 'tcp://molecule-docker.local:2375'
    purge_networks: true
    image: 'debian:11-slim'
    dockerfile: 'Dockerfile_debian11_systemd.j2'
    build_image: yes
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - verify  # MUST NOT make changes
    - idempotence
    - check
    - destroy
