---

- name: Zabbix | Debian | Installing basics
  ansible.builtin.import_tasks: install/all.yml
  tags: [install, agent, proxy, server]
  when: ZABBIX_CONFIG.state == 'present'

- name: Zabbix | Debian | Configuring basics
  ansible.builtin.import_tasks: configure/all.yml
  tags: [config, install, agent, proxy, server]

- name: Zabbix | Debian | Configuring MariaDB database
  ansible.builtin.import_role:
    name: ansibleguy.infra_mariadb
  vars:
    mariadb:
      instances:
        zabbix: "{{ ZABBIX_MARIADB_INSTANCE }}"
  when:
    - ZABBIX_CONFIG.manage.db
    - ZABBIX_CONFIG.manage.server or ZABBIX_CONFIG.manage.proxy
  tags: [install, server, proxy]

- name: Zabbix | Debian | Processing Zabbix Server
  ansible.builtin.import_tasks: server.yml
  when: ZABBIX_CONFIG.manage.server
  tags: [config, install, uninstall, server]

- name: Zabbix | Debian | Processing Zabbix Proxy
  ansible.builtin.import_tasks: proxy.yml
  when: ZABBIX_CONFIG.manage.proxy
  tags: [config, install, uninstall, proxy]

- name: Zabbix | Debian | Processing Zabbix Agent
  ansible.builtin.import_tasks: agent.yml
  when: ZABBIX_CONFIG.manage.agent
  tags: [config, install, uninstall, agent]

- name: Zabbix | Debian | Uninstalling basics
  ansible.builtin.import_tasks: uninstall/all.yml
  when: ZABBIX_CONFIG.state != 'present'
  tags: [uninstall, agent, server, proxy]
