---

- name: Zabbix | Debian | Getting installed packages
  ansible.builtin.package_facts:
    manager: auto
  tags: [config, install, uninstall, agent, proxy, server]

- name: Zabbix | Debian | Installing basics
  ansible.builtin.import_tasks: install/all.yml
  tags: [install, agent, proxy, server]
  when: ZABBIX_CONFIG.state == 'present'

- name: Zabbix | Debian | Configuring basics
  ansible.builtin.import_tasks: configure/all.yml
  when: ZABBIX_CONFIG.state == 'present'
  tags: [config, install, agent, proxy, server]

- name: Zabbix | Debian | Processing Zabbix Server
  ansible.builtin.import_tasks: server.yml
  when: ZABBIX_CONFIG.manage.server
  tags: [config, install, uninstall, server]

- name: Zabbix | Debian | Processing Zabbix Proxy
  ansible.builtin.import_tasks: proxy.yml
  when: ZABBIX_CONFIG.manage.proxy
  tags: [config, install, uninstall, proxy]

- name: Zabbix | Debian | Processing Zabbix Agent
  ansible.builtin.include_tasks: agent.yml
  vars:
    agent: "{{ ZABBIX_CONFIG.agent }}"
  when:
    - ZABBIX_CONFIG.manage.agent
    - not ZABBIX_CONFIG.manage.agent2
  tags: [config, install, uninstall, agent]

- name: Zabbix | Debian | Processing Zabbix Agent2
  ansible.builtin.include_tasks: agent.yml
  vars:
    agent: "{{ ZABBIX_CONFIG.agent2 }}"
  when: ZABBIX_CONFIG.manage.agent2
  tags: [config, install, uninstall, agent]

- name: Zabbix | Debian | Uninstalling basics
  ansible.builtin.import_tasks: uninstall/all.yml
  when: ZABBIX_CONFIG.state != 'present'
  tags: [uninstall, agent, server, proxy]

- name: Zabbix | Debian | Cleaning up temporary password files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tmp_pwd_file_prefix }}_ps"
    - "{{ tmp_pwd_file_prefix }}_agent"
