---

- name: Zabbix | Installing dependencies
  ansible.builtin.apt:
    name: 'python3-apt'
  tags: [config, install, uninstall, agent, proxy, server]

- name: Zabbix | Getting installed packages
  ansible.builtin.package_facts:
    manager: 'apt'
  tags: [config, install, uninstall, agent, proxy, server]

- name: Zabbix | Installing basics
  ansible.builtin.include_tasks: install/all.yml
  tags: [install, agent, proxy, server]
  args:
    apply:
      tags: [install, agent, proxy, server]
  when: ZABBIX_CONFIG.state == 'present'

- name: Zabbix | Configuring basics
  ansible.builtin.include_tasks: configure/all.yml
  when: ZABBIX_CONFIG.state == 'present'
  args:
    apply:
      tags: [config, install, agent, proxy, server]
  tags: [config, install, agent, proxy, server]

- name: Zabbix | Processing Zabbix Server
  ansible.builtin.include_tasks: server.yml
  when: ZABBIX_CONFIG.manage.server | bool
  args:
    apply:
      tags: [config, install, uninstall, server]
  tags: [config, install, uninstall, server]

- name: Zabbix | Processing Zabbix Proxy
  ansible.builtin.include_tasks: proxy.yml
  when: ZABBIX_CONFIG.manage.proxy | bool
  args:
    apply:
      tags: [config, install, uninstall, proxy]
  tags: [config, install, uninstall, proxy]

- name: Zabbix | Processing Zabbix Agent
  ansible.builtin.include_tasks: agent.yml
  vars:
    agent: "{{ ZABBIX_CONFIG.agent1 }}"
    vers: 1
  when: ZABBIX_CONFIG.manage.agent1 | bool
  tags: [config, install, uninstall, agent]
  args:
    apply:
      tags: [config, install, uninstall, agent]

- name: Zabbix | Processing Zabbix Agent2
  ansible.builtin.include_tasks: agent.yml
  vars:
    agent: "{{ ZABBIX_CONFIG.agent2 }}"
    vers: 2
  when:
    - ZABBIX_CONFIG.manage.agent2 | bool
    - not ZABBIX_CONFIG.manage.agent1 | bool
  tags: [config, install, uninstall, agent]
  args:
    apply:
      tags: [config, install, uninstall, agent]

- name: Zabbix | Uninstalling basics
  ansible.builtin.include_tasks: uninstall/all.yml
  when: ZABBIX_CONFIG.state != 'present'
  args:
    apply:
      tags: [uninstall, agent, server, proxy]
  tags: [uninstall, agent, server, proxy]

- name: Zabbix | Cleaning up temporary password files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tmp_pwd_file_prefix }}_ps"
    - "{{ tmp_pwd_file_prefix }}_agent"
  delegate_to: localhost
  become: false
  changed_when: false
