---

- name: Zabbix | Proxy | Uninstalling
  ansible.builtin.include_tasks: uninstall/proxy.yml
  when:
    - ZABBIX_CNF.state != 'present'
    - "'zabbix-proxy-mysql' in ansible_facts.packages"
  args:
    apply:
      tags: [uninstall, proxy]
  tags: [uninstall, proxy]

# todo: simplify and accept database=sqlite



- name: Zabbix | Proxy | Configuring
  ansible.builtin.import_tasks: configure/proxy.yml
  when: ZABBIX_CNF.state == 'present'
