---

- name: Zabbix | Debian | Proxy | Uninstalling
  ansible.builtin.import_tasks: uninstall/proxy.yml
  when: ZABBIX_CONFIG.state != 'present'
  tags: [uninstall, proxy]

- name: Zabbix | Debian | Proxy | Verifying config
  ansible.builtin.fail:
    msg: "Not all needed settings were provided! Zabbix-Proxy cannot be configured! 
    We need: 'Server', 'TLSPSKIdentity or TLSCertFile', 'tls_psk or TLSKeyFile', 
    db managed by role or 'DBName' and 'DBSocket' for a local database or 'DBHost' and 'DBPort' for a remote database!
    Also: unencrypted connections are not allowed!"
  when: >
    ZABBIX_CONFIG.state == 'present' and
    cnf.Server in NONE_VALUES or
    (cnf.TLSPSKIdentity in NONE_VALUES and cnf.TLSCertFile in NONE_VALUES) or
    (ZABBIX_CONFIG.proxy.tls_psk in NONE_VALUES and (ZABBIX_CONFIG.proxy.tls_cert_copy in NONE_VALUES or
    ZABBIX_CONFIG.proxy.tls_key_copy in NONE_VALUES or ZABBIX_CONFIG.proxy.tls_ca_copy in NONE_VALUES) or
    (not ZABBIX_CONFIG.manage.db and (cnf.DBSocket in NONE_VALUES or (cnf.DBHost in NONE_VALUES and cnf.DBPort in NONE_VALUES))) or
    (not ZABBIX_CONFIG.manage.db and cnf.DBName in NONE_VALUES) or
    (TLSConnect == 'unencrypted' or TLSAccept == 'unencrypted')
  vars:
    cnf: ZABBIX_CONFIG.proxy.settings

- name: Zabbix | Debian | Proxy | Installing
  ansible.builtin.import_tasks: install/proxy.yml
  when: ZABBIX_CONFIG.state == 'present'
  tags: [install, proxy]

- name: Zabbix | Debian | Proxy | Configuring
  ansible.builtin.import_tasks: configure/proxy.yml
  when: ZABBIX_CONFIG.state == 'present'
