---

- name: Zabbix | Proxy | Uninstalling
  ansible.builtin.include_tasks: uninstall/proxy.yml
  when:
    - ZABBIX_CONFIG.state != 'present'
    - "'zabbix-proxy-mysql' in ansible_facts.packages"
  args:
    apply:
      tags: [uninstall, proxy]
  tags: [uninstall, proxy]

- name: Zabbix | Proxy | Verifying config
  ansible.builtin.fail:
    msg: "Not all needed settings were provided! Zabbix-Proxy cannot be configured!
    We need: 'Server', 'TLSPSKIdentity or TLSCertFile', 'tls_psk (longer than {{ ZABBIX_HC.psk_min_length }} characters) or TLSKeyFile',
    db managed by role or 'DBName' and 'DBSocket' for a local database or 'DBHost' and 'DBPort' for a remote database!
    Also: unencrypted connections are not allowed!"
  when: >
    ZABBIX_CONFIG.state == 'present' and (
      ZABBIX_CONFIG.proxy.settings.Server in NONE_VALUES or (
        ZABBIX_CONFIG.proxy.settings.TLSPSKIdentity in NONE_VALUES and
        ZABBIX_CONFIG.proxy.settings.TLSCertFile in NONE_VALUES
      ) or (
        ZABBIX_CONFIG.proxy.tls_psk in NONE_VALUES and (
          ZABBIX_CONFIG.proxy.tls_cert_copy in NONE_VALUES or
          ZABBIX_CONFIG.proxy.tls_key_copy in NONE_VALUES or
          ZABBIX_CONFIG.proxy.tls_ca_copy in NONE_VALUES
        ) or (
          not ZABBIX_CONFIG.manage.db | bool and (
            ZABBIX_CONFIG.proxy.settings.DBSocket in NONE_VALUES or (
              ZABBIX_CONFIG.proxy.settings.DBHost in NONE_VALUES and
              ZABBIX_CONFIG.proxy.settings.DBPort in NONE_VALUES
            )
          )
        ) or (
          not ZABBIX_CONFIG.manage.db | bool and
          ZABBIX_CONFIG.proxy.settings.DBName in NONE_VALUES
        ) or (
          ZABBIX_CONFIG.proxy.settings.TLSConnect == 'unencrypted' or
          ZABBIX_CONFIG.proxy.settings.TLSAccept == 'unencrypted'
        ) or (
          ZABBIX_CONFIG.proxy.tls_psk | zabbix_psk_hex | length < ZABBIX_HC.psk_min_length
        )
      )
    )

- name: Zabbix | Proxy | Installing
  ansible.builtin.include_tasks: install/proxy.yml
  when: ZABBIX_CONFIG.state == 'present'
  args:
    apply:
      tags: [install, proxy]
  tags: [install, proxy]

- name: Zabbix | Proxy | Configuring
  ansible.builtin.import_tasks: configure/proxy.yml
  when: ZABBIX_CONFIG.state == 'present'
