---

- name: Zabbix | Debian | Server | Uninstalling
  ansible.builtin.import_tasks: uninstall/server.yml
  when:
    - ZABBIX_CONFIG.state != 'present'
    - "'zabbix-server-mysql' in ansible_facts.packages or 'zabbix-frontend-php' in ansible_facts.packages"
  tags: [uninstall, server]

- name: Zabbix | Debian | Server | Verifying config
  ansible.builtin.fail:
    msg: "Not all needed settings were provided! Zabbix-Server cannot be configured!
    We need: db managed by role or 'DBName' and 'DBSocket' for a local database or 'DBHost' and 'DBPort' for a remote database!
    Also: unencrypted connections are not allowed!"
  when: >
    ZABBIX_CONFIG.state == 'present' and (
      not ZABBIX_CONFIG.manage.db | bool and (
        ZABBIX_CONFIG.server.settings.DBSocket in NONE_VALUES or (
          ZABBIX_CONFIG.server.settings.DBHost in NONE_VALUES and
          ZABBIX_CONFIG.server.settings.DBPort in NONE_VALUES
        )
      ) or (
        not ZABBIX_CONFIG.manage.db | bool and
        ZABBIX_CONFIG.server.settings.DBName in NONE_VALUES
      )
    )

- name: Zabbix | Debian | Server | Installing
  ansible.builtin.import_tasks: install/server.yml
  when: ZABBIX_CONFIG.state == 'present'
  tags: [install, server]

- name: Zabbix | Debian | Server | Configuring
  ansible.builtin.import_tasks: configure/server.yml
  when: ZABBIX_CONFIG.state == 'present'
  tags: [config, server]
