---

- name: Zabbix | Debian | Configure | Agent2 | Creating agent directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: 'root'
    group: 'root'
    mode: 0755
  loop:
    - "{{ agent.path_userparameters }}"
    - "{{ agent.path_scripts }}"

- name: Zabbix | Debian | Configure | Agent2 | Copying provided scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ agent.path_scripts }}/"
    owner: 'root'
    group: "{{ ZABBIX_HC.group }}"
    mode: "{{ ZABBIX_CONFIG.mode_scripts }}"
  with_fileglob: "files/agent2/scripts/*"

- name: Zabbix | Debian | Configure | Agent2 | Copying provided userparameters
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ agent.path_userparameters }}/"
    owner: 'root'
    group: "{{ ZABBIX_HC.group }}"
    mode: 0640
  with_fileglob: "files/agent2/userparameters/*"

- name: Zabbix | Debian | Configure | Agent2 | Deploying tls-psk
  ansible.builtin.copy:
    content: "{{ agent.tls_psk }}"
    dest: "{{ ZABBIX_CONFIG.path_private }}/agent2_psk.txt"
    owner: 'root'
    group: "{{ ZABBIX_HC.group }}"
    mode: 0640
  when: agent.tls_psk not in NONE_VALUES

- name: Zabbix | Debian | Configure | Agent2 | Deploying tls certificate
  ansible.builtin.import_tasks: tls_cert.yml
  vars:
    config: "{{ agent }}"
    prefix: 'agent2'
  when:
    - agent.tls_ca_copy not in NONE_VALUES
    - agent.tls_cert_copy not in NONE_VALUES
    - agent.tls_key_copy not in NONE_VALUES

- name: Zabbix | Debian | Configure | Agent2 | Deploying config
  ansible.builtin.template:
    src: 'templates/etc/zabbix/zabbix_agent.conf.j2'
    dest: "{{ ZABBIX_HC.file_config_agent2 }}"
    owner: 'root'
    group: "{{ ZABBIX_HC.group }}"
    mode: 0640
  no_log: true  # since passwords are written to the file

- name: Zabbix | Debian | Configure | Agent2 | Restarting service
  ansible.builtin.systemd:
    name: "{{ ZABBIX_HC.service.agent2 }}"
    state: restarted
    no_block: true
  changed_when: false
