---

- name: Zabbix | Configure | Apache2 status page | Configuring listen-port
  ansible.builtin.lineinfile:
    path: '/etc/apache2/ports.conf'
    line: "Listen {{ ZABBIX_CONFIG.apache.status_page.port }}"
  ignore_errors: true

- name: Zabbix | Configure | Apache2 status page | Configuring site
  ansible.builtin.template:
    src: 'templates/etc/apache2/sites-available/status.conf.j2'
    dest: '/etc/apache2/sites-available/status.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: zbx_server_a2status_conf

- name: Zabbix | Configure | Apache2 status page | Enabling site
  ansible.builtin.file:
    state: link
    src: '/etc/apache2/sites-available/status.conf'
    dest: '/etc/apache2/sites-enabled/status.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  register: zbx_server_a2status_add
